"""empty message

Revision ID: 3cbc239d0e0b
Revises: 7e0ae727f97d
Create Date: 2020-05-21 07:35:23.840421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbc239d0e0b'
down_revision = '7e0ae727f97d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_index('ix_subscribers_email', table_name='subscribers')
    op.create_index(op.f('ix_subscribers_email'), 'subscribers', ['email'], unique=False)
    op.create_foreign_key(None, 'subscribers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscribers', type_='foreignkey')
    op.drop_index(op.f('ix_subscribers_email'), table_name='subscribers')
    op.create_index('ix_subscribers_email', 'subscribers', ['email'], unique=True)
    op.drop_column('subscribers', 'user_id')
    # ### end Alembic commands ###
